In [ ]:
# ============================================================
# 1. IMPORTACIÓN DE LIBRERÍAS
# ============================================================

import pandas as pd
import numpy as np

print("Librerías cargadas correctamente.")

Librerías cargadas correctamente.

In [ ]:
# ============================================================
# 2. CARGA DE MÓDULOS ENDES 2022
# ============================================================

rech0 = pd.read_csv(
    "RECH0.csv",
    encoding="latin-1",
    low_memory=False
)

rech6 = pd.read_csv(
    "RECH6.csv",
    encoding="latin-1",
    low_memory=False
)

print("RECH0:", rech0.shape)
print("RECH6:", rech6.shape)

RECH0: (37350, 1)
RECH6: (22424, 41)

In [ ]:
# ============================================================
# 2. CARGA CORRECTA DE MÓDULOS ENDES 2022
# ============================================================

import pandas as pd
import numpy as np

# RECH0 usa separador ;
rech0 = pd.read_csv(
    "RECH0.csv",
    sep=";",
    encoding="latin-1",
    low_memory=False
)

# RECH6 usa separador ,
rech6 = pd.read_csv(
    "RECH6.csv",
    sep=",",
    encoding="latin-1",
    low_memory=False
)

print("Dimensión RECH0:", rech0.shape)
print("Dimensión RECH6:", rech6.shape)

print("\nPrimeras columnas RECH0:")
print(rech0.columns[:10].tolist())

print("\nPrimeras columnas RECH6:")
print(rech6.columns[:10].tolist())

Dimensión RECH0: (37350, 44)
Dimensión RECH6: (22424, 41)

Primeras columnas RECH0:
['ï»¿ID1', 'HHID', 'HV000', 'HV001', 'HV002', 'HV002A', 'HV003', 'HV004', 'HV007', 'HV008']

Primeras columnas RECH6:
['ï»¿ID1', 'HHID', 'HC0', 'HC1', 'HC2', 'HC3', 'HC4', 'HC5', 'HC6', 'HC7']

In [ ]:
# ============================================================
# CARGA CORRECTA DE LOS MÓDULOS ENDES 2022
# ============================================================

import pandas as pd
import numpy as np

# RECH0 separado por punto y coma
rech0 = pd.read_csv(
    "RECH0.csv",
    sep=";",
    encoding="latin-1",
    low_memory=False
)

# RECH6 separado por coma
rech6 = pd.read_csv(
    "RECH6.csv",
    sep=",",
    encoding="latin-1",
    low_memory=False
)

print("RECH0:", rech0.shape)
print("RECH6:", rech6.shape)

RECH0: (37350, 44)
RECH6: (22424, 41)

In [ ]:
# ============================================================
# LIMPIEZA DE NOMBRES DE COLUMNAS
# ============================================================

rech0.columns = (
    rech0.columns
    .str.replace("\ufeff", "", regex=False)
    .str.replace("ï»¿", "", regex=False)
    .str.strip()
)

rech6.columns = (
    rech6.columns
    .str.replace("\ufeff", "", regex=False)
    .str.replace("ï»¿", "", regex=False)
    .str.strip()
)

print("Primeras columnas RECH0:")
print(rech0.columns[:10].tolist())

print("\nPrimeras columnas RECH6:")
print(rech6.columns[:10].tolist())

Primeras columnas RECH0:
['ID1', 'HHID', 'HV000', 'HV001', 'HV002', 'HV002A', 'HV003', 'HV004', 'HV007', 'HV008']

Primeras columnas RECH6:
['ID1', 'HHID', 'HC0', 'HC1', 'HC2', 'HC3', 'HC4', 'HC5', 'HC6', 'HC7']

In [ ]:
print("ID1 en RECH0:", "ID1" in rech0.columns)
print("ID1 en RECH6:", "ID1" in rech6.columns)

ID1 en RECH0: True
ID1 en RECH6: True

In [ ]:
# ============================================================
# VERIFICACIÓN DEL AÑO
# ============================================================

print("Años encontrados en RECH0:")
print(rech0["ID1"].value_counts(dropna=False))

print("\nAños encontrados en RECH6:")
print(rech6["ID1"].value_counts(dropna=False))

Años encontrados en RECH0:
ID1
2022    37350
Name: count, dtype: int64

Años encontrados en RECH6:
ID1
2022    22424
Name: count, dtype: int64

In [ ]:
# ============================================================
# 4. VERIFICACIÓN DE LA LLAVE HHID
# ============================================================

print("¿HHID existe en RECH0?", "HHID" in rech0.columns)
print("¿HHID existe en RECH6?", "HHID" in rech6.columns)

print("\nCantidad de registros:")
print("RECH0:", len(rech0))
print("RECH6:", len(rech6))

print("\nCantidad de HHID únicos:")
print("RECH0:", rech0["HHID"].nunique())
print("RECH6:", rech6["HHID"].nunique())

print("\nDuplicados de HHID en RECH0:")
print(rech0["HHID"].duplicated().sum())

¿HHID existe en RECH0? True
¿HHID existe en RECH6? True

Cantidad de registros:
RECH0: 37350
RECH6: 22424

Cantidad de HHID únicos:
RECH0: 37350
RECH6: 19315

Duplicados de HHID en RECH0:
0

In [ ]:
# ============================================================
# 5. INTEGRACIÓN DE RECH0 + RECH6
# ============================================================

endes_2022 = pd.merge(
    rech6,
    rech0,
    on="HHID",
    how="left",
    validate="many_to_one",
    suffixes=("_RECH6", "_RECH0")
)

print("Integración realizada correctamente.")

print("\nDimensión RECH6 antes de integrar:")
print(rech6.shape)

print("\nDimensión final después de integrar:")
print(endes_2022.shape)

Integración realizada correctamente.

Dimensión RECH6 antes de integrar:
(22424, 41)

Dimensión final después de integrar:
(22424, 84)

In [ ]:
# ============================================================
# 5.1 CONTROL DE LA INTEGRACIÓN
# ============================================================

sin_coincidencia = endes_2022["HV024"].isna().sum()

print("Registros de RECH6 sin coincidencia en RECH0:")
print(sin_coincidencia)

Registros de RECH6 sin coincidencia en RECH0:
0

In [ ]:
# ============================================================
# 5.2 VERIFICACIÓN DE REGISTROS
# ============================================================

print("Registros antes de integrar:", len(rech6))
print("Registros después de integrar:", len(endes_2022))

if len(rech6) == len(endes_2022):
    print(" No se perdieron registros durante la integración.")
else:
    print(" Revisar la integración.")

Registros antes de integrar: 22424
Registros después de integrar: 22424
 No se perdieron registros durante la integración.

Se integraron los módulos RECH0 y RECH6 mediante la variable HHID, conservando los registros infantiles de RECH6 e incorporando la información correspondiente del hogar. Se verificó posteriormente la correspondencia de los registros y la conservación del número total de observaciones.

In [ ]:
# ============================================================
# 6.1 VERIFICACIÓN DE DEPARTAMENTO
# ============================================================

print("Códigos encontrados en HV024:")

print(
    endes_2022["HV024"]
    .value_counts(dropna=False)
    .sort_index()
)

Códigos encontrados en HV024:
HV024
1      960
2      737
3      776
4      786
5      923
6      798
7      816
8      675
9      774
10     922
11     789
12     793
13     815
14     878
15    2643
16     994
17     798
18     682
19     746
20     892
21     657
22     871
23     799
24     916
25     984
Name: count, dtype: int64

In [ ]:
# ============================================================
# 6.2 REGISTROS DE PUNO
# ============================================================

registros_puno = (endes_2022["HV024"] == 21).sum()

print("Cantidad de registros de Puno:")
print(registros_puno)

Cantidad de registros de Puno:
657

In [ ]:
# ============================================================
# 6.3 FILTRO REGIÓN PUNO
# ============================================================

puno_2022 = endes_2022[
    endes_2022["HV024"] == 21
].copy()

print("Base filtrada para Puno:")
print(puno_2022.shape)

Base filtrada para Puno:
(657, 84)

In [ ]:
# ============================================================
# 6.4 VALIDACIÓN DEL FILTRO
# ============================================================

print("Valores de HV024 después del filtro:")
print(puno_2022["HV024"].unique())

if puno_2022["HV024"].nunique() == 1 and puno_2022["HV024"].iloc[0] == 21:
    print("✅ La base contiene únicamente registros de Puno.")
else:
    print("⚠️ Revisar el filtro de departamento.")

Valores de HV024 después del filtro:
[21]
✅ La base contiene únicamente registros de Puno.

Se realizó la selección geográfica de los registros correspondientes a la región Puno mediante la variable HV024. Posteriormente, se verificó que la base resultante contenga únicamente observaciones asociadas al departamento seleccionado.

La investigación se centra únicamente en niños de 6 a 35 meses de edad.
En el módulo RECH6, la variable:

In [ ]:
# ============================================================
# 7. SELECCIÓN DE NIÑOS DE 6 A 35 MESES
# ============================================================

puno_6_35_2022 = puno_2022[
    (puno_2022["HC1"] >= 6) &
    (puno_2022["HC1"] <= 35)
].copy()

print("Niños de 6 a 35 meses en Puno:")
print(puno_6_35_2022.shape)

Niños de 6 a 35 meses en Puno:
(325, 84)

In [ ]:
# ============================================================
# 7.1 VALIDACIÓN DEL RANGO DE EDAD
# ============================================================

print("Edad mínima:", puno_6_35_2022["HC1"].min(), "meses")
print("Edad máxima:", puno_6_35_2022["HC1"].max(), "meses")

print("\nNúmero de registros:")
print(len(puno_6_35_2022))

Edad mínima: 6 meses
Edad máxima: 35 meses

Número de registros:
325

In [ ]:
# ============================================================
# 7.2 COMPROBACIÓN AUTOMÁTICA
# ============================================================

if (
    puno_6_35_2022["HC1"].min() >= 6
    and puno_6_35_2022["HC1"].max() <= 35
):
    print("✅ Todos los registros están entre 6 y 35 meses.")
else:
    print("⚠️ Revisar el filtro de edad.")

✅ Todos los registros están entre 6 y 35 meses.

In [ ]:
# ============================================================
# 8. REVISIÓN DE LA VARIABLE HC57
# ============================================================

print("Valores encontrados en HC57:")

print(
    puno_6_35_2022["HC57"]
    .value_counts(dropna=False)
    .sort_index()
)

Valores encontrados en HC57:
HC57
1      4
2     92
3    121
4    101
9      7
Name: count, dtype: int64

In [ ]:
# ============================================================
# 8.1 DISTRIBUCIÓN PORCENTUAL DE HC57
# ============================================================

porcentaje_hc57 = (
    puno_6_35_2022["HC57"]
    .value_counts(normalize=True, dropna=False)
    .sort_index()
    * 100
).round(2)

print("Porcentaje por categoría de HC57:")
print(porcentaje_hc57)

Porcentaje por categoría de HC57:
HC57
1     1.23
2    28.31
3    37.23
4    31.08
9     2.15
Name: proportion, dtype: float64

Se realizó una revisión exploratoria de la variable HC57 con el propósito de identificar las categorías disponibles, su frecuencia y posibles valores faltantes antes de construir la variable objetivo binaria de anemia infantil.

PASO 9: Depuración y construcción de la variable objetivo
Descripción
En este paso vamos a conservar únicamente los registros con una clasificación válida de anemia y crear una variable binaria que luego usará el modelo.
Según el diccionario ENDES, HC57 corresponde al nivel de anemia y sus categorías son: 1 grave, 2 moderada, 3 leve y 4 sin anemia.     Diccionario - RECH6
Para el modelo definiremos:
1 = presenta anemia
0 = no presenta anemia

In [ ]:
# ============================================================
# 9.1 DEPURACIÓN DE LA VARIABLE HC57
# ============================================================

datos_2022 = puno_6_35_2022[
    puno_6_35_2022["HC57"].isin([1, 2, 3, 4])
].copy()

print("Registros antes de depurar:", len(puno_6_35_2022))
print("Registros válidos después de depurar:", len(datos_2022))

Registros antes de depurar: 325
Registros válidos después de depurar: 318

In [ ]:
# ============================================================
# 9.2 CREACIÓN DE LA VARIABLE OBJETIVO
# ============================================================

datos_2022["target_anemia"] = np.where(
    datos_2022["HC57"].isin([1, 2, 3]),
    1,
    0
)

print("Variable target_anemia creada correctamente.")

Variable target_anemia creada correctamente.

In [ ]:
# ============================================================
# 9.3 DISTRIBUCIÓN DE LA VARIABLE OBJETIVO
# ============================================================

print("Distribución de anemia:")

print(
    datos_2022["target_anemia"]
    .value_counts()
    .rename(index={
        1: "Con anemia",
        0: "Sin anemia"
    })
)

Distribución de anemia:
target_anemia
Con anemia    217
Sin anemia    101
Name: count, dtype: int64

In [ ]:
# ============================================================
# 9.4 DISTRIBUCIÓN PORCENTUAL
# ============================================================

distribucion = (
    datos_2022["target_anemia"]
    .value_counts()
    .rename(index={
        1: "Con anemia",
        0: "Sin anemia"
    })
    .to_frame("Frecuencia")
)

distribucion["Porcentaje"] = (
    distribucion["Frecuencia"]
    / len(datos_2022)
    * 100
).round(2)

distribucion

               Frecuencia  Porcentaje
target_anemia
Con anemia            217       68.24
Sin anemia            101       31.76

Se depuró la variable HC57, conservando únicamente los registros con clasificación válida de anemia. Posteriormente, se construyó la variable objetivo binaria target_anemia, asignando el valor 1 a los casos de anemia grave, moderada o leve, y el valor 0 a los niños sin anemia.

PASO 10: Resumen final del dataset 2022
Descripción
En esta etapa se genera un resumen general del conjunto de datos final, verificando:
- cantidad de registros;
- cantidad de variables;
- rango de edad;
- región analizada;
- distribución de anemia.

In [ ]:
# ============================================================
# 10.1 RESUMEN FINAL DEL DATASET 2022
# ============================================================

print("==========================================")
print("RESUMEN FINAL - ENDES 2022")
print("==========================================")

print("\nDimensión final:")
print(datos_2022.shape)

print("\nTotal de registros:")
print(len(datos_2022))

print("\nTotal de variables:")
print(datos_2022.shape[1])

print("\nDepartamento:")
print(datos_2022["HV024"].unique())

print("\nRango de edad:")
print("Edad mínima:", datos_2022["HC1"].min(), "meses")
print("Edad máxima:", datos_2022["HC1"].max(), "meses")

print("\nDistribución de anemia:")
print(
    datos_2022["target_anemia"]
    .value_counts()
    .rename(index={
        1: "Con anemia",
        0: "Sin anemia"
    })
)

==========================================
RESUMEN FINAL - ENDES 2022
==========================================

Dimensión final:
(318, 85)

Total de registros:
318

Total de variables:
85

Departamento:
[21]

Rango de edad:
Edad mínima: 6 meses
Edad máxima: 35 meses

Distribución de anemia:
target_anemia
Con anemia    217
Sin anemia    101
Name: count, dtype: int64

In [ ]:
# ============================================================
# 10.2 TABLA RESUMEN DEL PROCESAMIENTO
# ============================================================

resumen_2022 = pd.DataFrame({
    "Etapa": [
        "RECH0 original",
        "RECH6 original",
        "Base integrada RECH0 + RECH6",
        "Registros de Puno",
        "Niños de 6 a 35 meses",
        "Registros válidos para anemia"
    ],
    "Registros": [
        len(rech0),
        len(rech6),
        len(endes_2022),
        len(puno_2022),
        len(puno_6_35_2022),
        len(datos_2022)
    ]
})

resumen_2022

                           Etapa  Registros
0                 RECH0 original      37350
1                 RECH6 original      22424
2   Base integrada RECH0 + RECH6      22424
3              Registros de Puno        657
4          Niños de 6 a 35 meses        325
5  Registros válidos para anemia        318

In [ ]:
# ============================================================
# 10.3 TABLA DESCRIPTIVA DE ANEMIA
# ============================================================

tabla_anemia_2022 = (
    datos_2022["target_anemia"]
    .value_counts()
    .rename(index={
        1: "Con anemia",
        0: "Sin anemia"
    })
    .to_frame("Frecuencia")
)

tabla_anemia_2022["Porcentaje"] = (
    tabla_anemia_2022["Frecuencia"]
    / len(datos_2022)
    * 100
).round(2)

tabla_anemia_2022

               Frecuencia  Porcentaje
target_anemia
Con anemia            217       68.24
Sin anemia            101       31.76

In [ ]:
# ============================================================
# EXPORTAR DATASET FINAL 2022 A EXCEL
# Descripción: guardamos la base final en formato .xlsx
# para que cada variable aparezca en su propia columna.
# ============================================================

nombre_archivo = "ENDES_PUNO_ANEMIA_2022.xlsx"

datos_2022.to_excel(
    nombre_archivo,
    index=False
)

print("Archivo generado correctamente:")
print(nombre_archivo)

Archivo generado correctamente:
ENDES_PUNO_ANEMIA_2022.xlsx